account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import CustomLoginForm, CustomPasswordResetForm, CustomSetPasswordForm
from account import views
app_name = 'account'
urlpatterns = [
    path('send-otp', views.send_otp, name = 'send_otp'),
    path('verify-otp', views.verify_otp, name ='verify_otp'),
    path('create-account/', views.userCreationView, name='create_account' ),
    path('login/', auth_views.LoginView.as_view
    (template_name='user/login.html', authentication_form =CustomLoginForm ,next_page= 'home'), name= 'login' ),
    path('logout/', views.logoutView, name='logout'),
    
    path('admin-login/', auth_views.LoginView.as_view
    (template_name='super_admin/login.html', authentication_form =CustomLoginForm ,next_page= 'super_admin:home'), name= 'admin_login' ),
    path('admin-creation', views.AdminCreationView.as_view(), name='admin_creation'),
    path('admin-logout', views.adminLogoutView, name='admin_logout'),

]

appleshop/urls.py
# ================== appleshop URL Configuration ===============

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.forms import CustomLoginForm, CustomPasswordResetForm, CustomSetPasswordForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('super-admin/', include('super_admin.urls', namespace = 'super_admin')),
    path('', include('home.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('offers/', include('offers.urls', namespace='offers')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('products/', include('products.urls', namespace='products')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('account/', include('account.urls', namespace='account')),

    path('password-reset/', auth_views.PasswordResetView.as_view
    (template_name = 'user/password_reset.html', form_class = CustomPasswordResetForm), name = 'password_reset'),
    path('password-rest-done/', auth_views.PasswordResetDoneView.as_view
    (template_name = 'user/password_reset_done.html'), name = 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view
    (template_name = 'user/password_reset_confirm.html', form_class = CustomSetPasswordForm), name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view
    (template_name = 'user/password_reset_complete.html'), name = 'password_reset_complete'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart import views
app_name = 'cart'
urlpatterns = [
    
    path('', views.cartView, name = 'cart'),

    path('add-to-cart/', views.addToCartView, name= 'add_to_cart'),
    path('add-to-cart/<str:pk>/', views.addToCartBeforeLoginView, name= 'add_to_cart_brfore_login'),
    path('change-qty/', views.changeQtyView, name  = 'change_qty'),

]

home/urls.py
from django import views
from django.urls import path
from home import views

urlpatterns = [
    path('', views.homeView, name='home')
]

products/urls.py
from django.urls import path
from products import views
app_name = 'products'

urlpatterns = [
    path('product-list/<str:pk>/', views.productListView, name = 'product_list'),
    path('product-details/<str:pk>/', views.productDetailsView, name = 'product_details'),
]

profiles/urls.py
from django.urls import path
from profiles import views
app_name = 'profiles'
urlpatterns = [
    path('customer-profile/', views.CustomerProfileView.as_view(), name = 'customer_profile'),
    path('admin-profile/', views.AdminProfileView.as_view(), name = 'admin_profile'),
    path('address/', views.addressView, name = 'address'),
    path('address-delete/', views.addressDeleteView, name = 'address_delete'),
    path('address-edit/', views.addressEdit, name = 'address_edit'),
    path('address-default/', views.addressDefaultView, name = 'address_dafault'),
]

super_admin/urls.py
from django.urls import path
from super_admin import views

app_name = 'super_admin'
urlpatterns = [
    path('',views.homeView, name='home'),
    path('chart/',views.homeView, name='home'),

    path('category-add',views.CategoryAddView.as_view(), name='category_add'),
    path('category-list/', views.categoryListView, name= 'category_list'),
    path('category-details/<str:pk>', views.categoryDetailsView, name= 'category_details'),
    path('category-edit/<str:pk>', views.CategoryEditView.as_view(), name= 'category_edit'),
    path('category-delete/<str:pk>', views.categoryDeleteView, name= 'category_delete'),

    path('product-add',views.ProductAddView.as_view(), name='product_add'),
    path('product-list/', views.productListView, name= 'product_list'),
    path('product-details/<str:pk>', views.productDetailsView, name= 'product_details'),
    path('product-edit/<str:pk>', views.ProductEditView.as_view(), name= 'product_edit'),
    path('product-delete/<str:pk>', views.productDeleteView, name= 'product_delete'),

    path('coupon-add',views.couponAddView, name='coupon_add'),
    path('coupon-list/', views.couponListView, name= 'coupon_list'),
    path('coupon-edit/<str:pk>', views.CouponEditView.as_view(), name= 'coupon_edit'),
    path('coupon-delete/<str:pk>', views.couponDeleteView, name= 'coupon_delete'),

    path('order-list/', views.OrderListView.as_view(), name= 'order_list'),

    path('customer-list/', views.customerListView, name= 'customer_list'),
    path('admin-list/', views.adminListView, name= 'admin_list'),
    path('admin-request-list/', views.AdminRequestListView.as_view(), name= 'admin_request_list'),


]

profiles/models.py
from django.db import models
from account.models import CustomUser

STATE_CHOICES = (
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Bihar', 'Bihar'),
    ('Chhattisgarh', 'Chhattisgarh'),
    ('Goa','Goa'),
    ('Gujarat', 'Gujarat'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh'),
    ('Jharkhand', 'Jharkhand'),
    ('Karnataka', 'Karnataka'),
    ('Kerala', 'Kerala'),
    ('Madhya Pradesh', 'Madhya Pradesh'),
    ('Maharashtra', 'Maharashtra'),
    ('Manipur', 'Manipur'),
    ('Meghalaya', 'Meghalaya'),
    ('Mizoram', 'Mizoram'),
    ('Nagaland', 'Nagaland'),
    ('Odisha', 'Odisha'),
    ('Punjab', 'Punjab'),
    ('Rajasthan', 'Rajasthan'),
    ('Sikkim', 'Sikkim'),
    ('Tamil Nadu', 'Tamil Nadu'),
    ('Telangana', 'Telangana'),
    ('Tripura', 'Tripura'),
    ('Uttar Pradesh', 'Uttar Pradesh'),
    ('Uttarakhand', 'Uttarakhand'),
    ('West Bengal', 'West Bengal'),
    ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'),
    ('Chandigarh', 'Chandigarh'),
    ('Dadra & Nagar Haveli and Daman & Diu', 'Dadra & Nagar Haveli and Daman & Diu'),
    ('Delhi', 'Delhi'),
    ('Jammu and Kashmir', 'Jammu and Kashmir'),
    ('Lakshadweep', 'Lakshadweep'),
    ('Puducherry', 'Puducherry'),
    ('Ladakh', 'Ladakh')
)


class CustomerAddress(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    address = models.TextField()
    state = models.CharField(max_length=100, choices=STATE_CHOICES)
    pin = models.PositiveIntegerField()
    mob = models.PositiveIntegerField()
    edit = models.BooleanField(default=False)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.name


   

super_admin/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from account.models import CustomUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import password_validation
from django.contrib.auth.forms import (UserCreationForm, AuthenticationForm,
PasswordResetForm, SetPasswordForm)





class CustomUserCreationForm(UserCreationForm):
    # username = forms.CharField(
    #     widget=(forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'User Name'}))
    # )
    # email = forms.CharField(
    #     widget=forms.EmailInput(attrs={'class' : 'form-control', 'placeholder' : 'Email'})
    # )
    # mobile = forms.IntegerField(
    # widget=forms.NumberInput(attrs={'class' : 'form-control', 'placeholder' : 'Mobile'})
    # )
    # password1 = forms.CharField(
    #     widget=forms.PasswordInput(attrs={'class' : 'form-control', 'placeholder' : 'Password'})
    # )
    # password2 = forms.CharField(
    #     widget=forms.PasswordInput(attrs={'class' : 'form-control', 'placeholder' : 'Confirm Password'})
    # )


    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'mobile', 'password1', 'password2', 'is_admin_request' )

class CustomLoginForm(AuthenticationForm):
    username = forms.IntegerField(
        widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Mobile Number'}),
        
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class' : 'form-control', 'placeholder' : 'Password'})
    )


class CustomPasswordResetForm(PasswordResetForm):
        email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email", "class" : "form-control"}),
    )

class CustomSetPasswordForm(SetPasswordForm):
        new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class" : "form-control"}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
        new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class" : "form-control"}),
    )
        

home/views.py
from django.shortcuts import render
from category.models import Category
from products.models import Product


def homeView(request):
    categories = Category.objects.all().order_by('order_by')
    products_in_home = Product.objects.filter(is_visible_home_img = True).order_by('home_img_order')

    context = {
    'categories' : categories,
    'products_in_home' : products_in_home
    }
    return render(request, 'user/home.html', context)

profiles/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.views import View
from django.utils.decorators import method_decorator
from profiles.form import AddressForm, ProfileForm
from profiles.models import CustomerAddress 
from account.models import CustomUser

@method_decorator(login_required(login_url='account:login'), name='dispatch')
class CustomerProfileView(View):
    
    def get(self, request):
        form = AddressForm
        user = CustomUser.objects.get(username = request.user.username)
        profiles_form = ProfileForm(instance= user)
        addresses = CustomerAddress.objects.filter(user = request.user).order_by('-default')
        context = {
            'addresses' : addresses,
            'form' : form,
            'profiles_form' : profiles_form
        }
        return render(request, 'user/profile.html', context)
    def post(self, request):
        profile_form = ProfileForm( request.POST, request.FILES, instance= request.user)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Profile edited successfuly')
            return redirect('profiles:customer_profile')
        messages.error(request, 'Invalid data')
        return redirect('profiles:coustomer_profile')

@method_decorator(login_required(login_url='account:login'), name='dispatch')
class AdminProfileView(View):
    def get(self, request):
        profile_form = ProfileForm(instance= request.user)
        context = {
            'profile_form' : profile_form
        }
        return render(request, 'super_admin/profile.html', context)

    def post(self, request):
        user_profile_form = ProfileForm( request.POST, request.FILES, instance= request.user)
        if user_profile_form.is_valid():
            user_profile_form.save()
            messages.success(request, 'Profile edited successfuly')
            return redirect('profiles:admin_profile')
        messages.error(request, 'Invalid data')
        return redirect('profiles:admin_profile')



@login_required(login_url='account:login')
def addressView(request):

    if request.method == 'POST':
        default_address = CustomerAddress.objects.filter(user = request.user, default = True)
        for address in default_address:
            address.default = False
            address.save()
        name = request.POST.get('name')
        address = request.POST.get('address')
        state = request.POST.get('state')
        pin = request.POST.get('pin')
        mob = request.POST.get('mob')

        try:
            edit_address = CustomerAddress.objects.get(edit = True)
            edit_address.name = name
            edit_address.address = address
            edit_address.state = state
            edit_address.pin = pin
            edit_address.mob = mob
            edit_address.edit = False
            edit_address.default = True
            edit_address.save()

            print('update')
        except:
            CustomerAddress.objects.create(
            user = request.user, 
            name = name, 
            address = address, 
            state = state, 
            pin = pin, 
            mob = mob, 
            default = True
            )
            data = { 
                'status' : 'Product added successfully'
            }
            print('create')
            return JsonResponse(data)
    
    form = AddressForm
    context = {'form' : form }
    return render(request, 'user/profile.html', context)

@login_required(login_url='account:login')
def addressDefaultView(request):
    if request.method == 'POST':
        address_id = request.POST.get('address_id')
        all_address = CustomerAddress.objects.filter(user = request.user)
        for address in all_address:
            address.default = False
            address.save()
        address = CustomerAddress.objects.get(user = request.user, id = address_id)
        address.default = True
        address.save()
        data = { 
            'status' : 'set to default'
        }
        return JsonResponse(data)

@login_required(login_url='account:login')
def addressDeleteView(request):
    if request.method == 'POST':
        address_id = request.POST.get('address_id')
        address = CustomerAddress.objects.get(user = request.user, id = address_id)
        address.delete()
        data = { 
            'status' : 'Product added successfully'
        }
        return JsonResponse(data)


@login_required(login_url='account:login')
def addressEdit(request):
    if request.method == 'POST':
        address_id = request.POST.get('address_id')
        address = CustomerAddress.objects.get(user = request.user, id = address_id)
        address.edit = True
        address.save()
        data = {
            'name' : address.name,
            'address' : address.address,
            'state' : address.state,
            'pin' : address.pin,
            'mob' : address.mob
        }
        return JsonResponse(data)

templates/super_admin/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Admin | {% block title %} {% endblock title %}</title>

  <!-- ==============Bootstrap CSS==================== -->

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
  <!-- ==============fontAwesome kit's code================ -->

  <script src="https://kit.fontawesome.com/27e48654a9.js" crossorigin="anonymous"></script>

  <!-- Layout styles -->
  <link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
  <!-- End layout styles -->

  {% block css%}
  {% endblock %}
</head>

<body class="">
  <div class="container-scroller">
    <!-- partial:partials/_sidebar.html -->
    {% include 'super_admin/includes/sidebar.html' %}
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_navbar.html -->
      {% include 'super_admin/includes/navbar.html' %}
      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
          {% if messages %}
          {% for msg in messages %}
          <div class="alert {% if msg.tags %} alert-{{msg.tags}} {% endif %} alert-dismissible fade show" role="alert">
            <strong class="text-center">{{msg}}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
          {% endif %}

          {% block content %}
          {% endblock %}

        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        {% include 'super_admin/includes/footer.html' %}
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <script src="{% static 'admin/vendors/js/vendor.bundle.base.js' %}"></script>
  <script src="{% static 'admin/js/off-canvas.js' %}"></script>
  <!-- <script src="{% static 'admin/js/misc.js' %}"></script> -->

  <!-- ============ Bootstrap Bundle with Popper=========== -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  {% block link %}
  {% endblock %}

  <script src="{% static 'admin/js/script.js' %}"></script>

</body>

</html>

templates/super_admin/coupon_list.html
{% extends 'super_admin/base.html' %}
{% load static %}
{% block title %} Coupon list {% endblock title %}

{% block content %}
<div class="row ">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">coupon List</h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th> Coupon Name </th>
                                <th> Coupon Code </th>
                                <th> Discount (Rs) </th>
                                <th> Redeem</th>
                                <th> Active</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for coupon in coupons %}
                            <tr>

                                <td> {{coupon.coupon_name}} </td>
                                <td> {{coupon.coupon_code}} </td>
                                <td> {{coupon.discount}} </td>
                                <td>
                                    {% if coupon.is_redeemed %}
                                    <div class="text-danger">Redeemed</div>
                                    {% else %}
                                    <div class="text-success">Not Redeemed</div>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if coupon.is_active %}
                                    <div class="text-success">Active</div>
                                    {% else %}
                                    <div class="text-danger">Not Active</div>
                                    {% endif %}
                                </td>
                                <td>
                                    <a a href="{% url 'super_admin:coupon_edit' coupon.id %}"><i
                                            class="fa-solid fa-pen-to-square"></i></a>
                                </td>
                                <td>

                                    <!-- Button trigger modal -->
                                    <div type="button" class="" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                        <i class="fa-solid fa-trash text-danger"></i>
                                    </div>

                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModal" tabindex="-1"
                                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Delete coupon</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                        aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    Are you sure you want to delete the selected coupon?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary"
                                                        data-bs-dismiss="modal">Close</button>
                                                    <a href="{% url 'super_admin:coupon_delete' coupon.id %}"
                                                        type="button" class="btn btn-danger">Delete</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/super_admin/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- ==============Bootstrap CSS==================== -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />

    <!-- ==============fontAwesome kit's code================ -->

    <script src="https://kit.fontawesome.com/27e48654a9.js" crossorigin="anonymous"></script>

    <title>Admin | Login</title>
</head>

<body>



    <div class="container my-lg-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <div class="shadow p-3 mb-5 bg-body rounded">

                    {% if messages %} {% for message in messages %}
                    <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>
                        {{message}}
                    </p>
                    {% endfor %} {% endif %}

                    <h3>Admin Login</h3>
                    <hr>
                    {% if form.non_field_errors %} {% for error in form.non_field_errors %}
                    <p class="alert alert-danger my-3">{{error}}</p>
                    {% endfor %} {% endif %}
                    <form action="" method="post">
                        {% csrf_token %}
                        {% for form in form %}
                        <div class="form-group my-4">
                            {{form}}
                            <small class="text-danger">{{form.errors|striptags }}</small>
                        </div>
                        {% endfor %}

                        <div class="row mt-3">
                            <div class="col-lg-6 p-lg-3  ">
                                <button type="submit" class="btn btn-warning px-5  me-auto fw-bold w-100">LOGIN</button>
                            </div>
                            <div class="col-lg-6 p-lg-3 mt-3 mt-lg-0">
                                <a class="btn btn-primary px-5  fw-bold w-100"
                                    href="{% url 'account:admin_creation' %}">
                                    SIGNUP
                                </a>
                            </div>
                        </div>
                        <a class="text-decoration-none" href="{% url 'password_reset' %}">
                            <p class="text-primary text-center m-3 fw-bold"> Forgot Password ?</p>
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

templates/super_admin/order_list.html
{% extends 'super_admin/base.html' %}
{% load static %}
{% block title %} Order list {% endblock title %}

{% block content %}
<div class="row ">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">order List</h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th> User </th>
                                <th> product </th>
                                <th> Selling Price </th>
                                <th> Payment </th>
                                <th> Qty</th>
                                <th> Coupon (Rs)</th>
                                <th> Status</th>
                                <th> Updated</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in orders %}
                            <tr>
                                <td> {{order.user}} </td>
                                <td>
                                    <a href="{% url 'super_admin:product_details' order.product_id %}">
                                        <img src="{{order.image.url}}" alt="image" />
                                        <span class="pl-2 text-capitalize">{{order.product}}</span>
                                    </a>
                                </td>

                                <td> {{order.product_selling_price}} </td>
                                <td> {{order.payment}} </td>
                                <td> {{order.qty}} </td>
                                <td> {{order.coupon}} </td>
                                <td>

                                    <!-- Button trigger modal -->
                                    <div type="button" class="text-capitalize
                                    text-{% if order.status == 'success' %}light 
                                    text-{% elif order.status == 'shipped' %}primary 
                                    text-{% elif order.status == 'out_of_selivery' %}info 
                                    text-{% elif order.status == 'deliverd' %}success 
                                    text-{% elif order.status == 'cancelled' %}danger {%endif%}" data-bs-toggle="modal"
                                        data-bs-target="#id{{order.id}}">
                                        {{order.status}}
                                    </div>

                                    <!-- Modal -->
                                    <div class="modal fade" id="id{{order.id}}" tabindex="-1"
                                        aria-labelledby="{{order.id}}Label1" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <form action="" method="post">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="order_id" value="{{order.id}}">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="{{order.id}}Label">Delete order</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                            aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body">

                                                        <select name="status" required="">
                                                            <option class="text-capitalize" value="" selected="">
                                                                {{order.status}}</option>

                                                            <option class="bg-success" value="success">Success</option>

                                                            <option class="bg-primary" value="shipped">Shipped</option>

                                                            <option class="bg-info" value="out of selivery">Out of
                                                                delivery
                                                            </option>

                                                            <option class="bg-success" value="deliverd">Deliverd
                                                            </option>

                                                            <option class="bg-danger" value="cancelled">Cancelled
                                                            </option>

                                                        </select>

                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary"
                                                            data-bs-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-ingo">Save</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td> {{order.updated_at}} </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}