account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import CustomLoginForm, CustomPasswordResetForm, CustomSetPasswordForm
from account import views
app_name = 'account'
urlpatterns = [
    path('send-otp', views.send_otp, name = 'send_otp'),
    path('verify-otp', views.verify_otp, name ='verify_otp'),
    path('create-account/', views.userCreationView, name='create_account' ),
    path('login/', auth_views.LoginView.as_view
    (template_name='user/login.html', authentication_form =CustomLoginForm ,next_page= 'home'), name= 'login' ),
    path('logout/', views.logoutView, name='logout'),
    
    path('admin-login/', auth_views.LoginView.as_view
    (template_name='super_admin/login.html', authentication_form =CustomLoginForm ,next_page= 'super_admin:home'), name= 'admin_login' ),
    path('admin-creation', views.AdminCreationView.as_view(), name='admin_creation'),
    path('admin-logout', views.adminLogoutView, name='admin_logout'),

]

appleshop/urls.py
# ================== appleshop URL Configuration ===============

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.forms import CustomLoginForm, CustomPasswordResetForm, CustomSetPasswordForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('super-admin/', include('super_admin.urls', namespace = 'super_admin')),
    path('', include('home.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('offers/', include('offers.urls', namespace='offers')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('products/', include('products.urls', namespace='products')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('account/', include('account.urls', namespace='account')),

    path('password-reset/', auth_views.PasswordResetView.as_view
    (template_name = 'user/password_reset.html', form_class = CustomPasswordResetForm), name = 'password_reset'),
    path('password-rest-done/', auth_views.PasswordResetDoneView.as_view
    (template_name = 'user/password_reset_done.html'), name = 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view
    (template_name = 'user/password_reset_confirm.html', form_class = CustomSetPasswordForm), name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view
    (template_name = 'user/password_reset_complete.html'), name = 'password_reset_complete'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart import views
app_name = 'cart'
urlpatterns = [
    
    path('', views.cartView, name = 'cart'),

    path('add-to-cart/', views.addToCartView, name= 'add_to_cart'),
    path('add-to-cart/<str:pk>/', views.addToCartBeforeLoginView, name= 'add_to_cart_brfore_login'),
    path('change-qty/', views.changeQtyView, name  = 'change_qty'),

]

orders/urls.py
from django.urls import path
from orders import views
app_name = 'orders'
urlpatterns = [
    path('single-order/<str:pk>/', views.singleOrderView, name = 'single_order'),
    path('cart-order/', views.cartOrderView, name = 'cart_order'),
    path('your-order/', views.yourOrderView, name = 'your_order'),

    path('payment', views.paymentView),
    path('razorpay/', views.razorpayKey)

]

products/urls.py
from django.urls import path
from products import views
app_name = 'products'

urlpatterns = [
    path('product-list/<str:pk>/', views.productListView, name = 'product_list'),
    path('product-details/<str:pk>/', views.productDetailsView, name = 'product_details'),
]

profiles/urls.py
from django.urls import path
from profiles import views
app_name = 'profiles'
urlpatterns = [
    path('customer-profile/', views.CustomerProfileView.as_view(), name = 'customer_profile'),
    path('admin-profile/', views.AdminProfileView.as_view(), name = 'admin_profile'),
    path('address/', views.addressView, name = 'address'),
    path('address-delete/', views.addressDeleteView, name = 'address_delete'),
    path('address-edit/', views.addressEdit, name = 'address_edit'),
    path('address-default/', views.addressDefaultView, name = 'address_dafault'),
]

templates/user/includes/address.html
<div class="container load_address  ">

    <div class="d-flex flex-column align-items-center pt-4">
        <div class="shadow p-0 p-md-3 mb-5 bg-body rounded w-100">
            <h4 class="p-3">Address</h4>


            <div class="row address_load">
                <div class="col-lg-3 d-flex align-items-center justify-content-center">
                    <div role="button" data-bs-toggle="modal" data-bs-target="#address">
                        <h1 class="text-success p-3 p-lg-0"><i class="fa-solid fa-circle-plus fs-1"></i></h1>
                    </div>
                    <!-- Modal -->
                    <div class="modal fade" id="address" data-bs-backdrop="static" data-bs-keyboard="false"
                        tabindex="-1" aria-labelledby="addressLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="addressLabel">Address Form</h5>
                                    <button type="button" class="btn-close btn-danger" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                                </div>

                                <div class="modal-body">
                                    {% csrf_token %}
                                    {{form}}
                                    <div id="address-footer"></div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" id="btn-close" class="btn btn-danger"
                                        data-bs-dismiss="modal">Close</button>
                                    <button id="btn-save" class="address_save_btn btn btn-warning">SAVE</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% for address in addresses %}
                <div class="col-lg-4 p-2 ">
                    <div
                        class="address_closest_cls card  {% if address.default %} shadow p-1 mb-1 bg-body rounded {% endif%}">
                        <div class="card-body">
                            <h5 class="card-title">{{address.name}}</h5>
                            <p class="card-text">{{address.address}}, {{address.pin}}, {{address.mob}}</p>
                            {% csrf_token %}
                            <input type="hidden" class="address_id" value="{{address.id}}">
                            {% if address.default %}
                            <button class="address_default_btn btn btn-sm btn-success"><i
                                    class="fa-solid fa-check"></i></button>
                            {% else %}
                            <button class="address_default_btn btn btn-sm btn-warning">DEFAULT</button>
                            {% endif%}
                            <button data-bs-toggle="modal" data-bs-target="#address"
                                class="address_edit_btn btn btn-sm btn-secondary my-2 my-lg-0 mx-lg-3"><i
                                    class="fa-solid fa-pen-to-square"></i></button>
                            <button class="address_delete_btn btn btn-sm btn-danger"><i
                                    class="fa-solid fa-trash"></i></button>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>


        <!-- <div class="address_form address_add address_remove shadow p-3 mb-5 bg-body rounded p-lg-5"
            style="position: absolute; top: 300px;">
            <button class="address_close_btn btn btn-danger float-end m-0 p-0" style="width: 40px;">X</button>

            {% csrf_token %}
            <h4 class="text-warning">Your Addresses</h4>
            <hr class="text-success">

            {{form}}
            <button class="address_save_btn btn btn-warning mt-4">SAVE</button>

        </div> -->


    </div>

</div>

templates/user/includes/footer.html
<footer class="footer mx-3 d-none d-lg-block">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © cb-apple-shop
            2022 | This website is only for educational puposes.</span>

    </div>
</footer>

templates/user/includes/navbar.html
{% load static %}
<nav class=" nav_position navbar navbar-expand-lg navbar-dark nav_color py-lg-0">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}"><i class="fa-solid fa-apple-whole"></i>&nbspshop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <form action="{% url 'products:product_list' 'search' %}"
      class="search d-flex align-items-center m-auto ms-lg-5 mt-3 mb-lg-3">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search_input" />
      <button class="btn btn-outline-warning" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul
        class="navbar-nav ms-auto mb-2 mb-lg-0 text-uppercase fw-bold d-flex flex-sm-column align-items-center flex-lg-row">
        <li class="nav-item dropdown p-0">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            <button class="btn btn-dark">Product</button>
          </a>
          <ul class="dropdown-menu dropdown-menu-dark pe-2" aria-labelledby="navbarDropdown">
            <li><a href="{% url 'products:product_list' 'mac' %}" class="dropdown-item">Mac</a></li>
            <li><a href="{% url 'products:product_list' 'ipad' %}" class="dropdown-item">iPad</a></li>
            <li><a href="{% url 'products:product_list' 'iphone' %}" class="dropdown-item">iPhone</a></li>
            <li><a href="{% url 'products:product_list' 'watch' %}" class="dropdown-item">Watch</a></li>
            <li><a href="{% url 'products:product_list' 'airpods' %}" class="dropdown-item">AirPods</a></li>
            <li><a href="{% url 'products:product_list' 'homepod' %}" class="dropdown-item">HomePod</a></li>
          </ul>
        </li>
        {% if request.user.is_authenticated %}

        <li class="nav-item pe-2">
          <a class="nav-link text-white" href="{% url 'cart:cart' %}">

            <button type="button" class=" btn btn-dark position-relative">
              <i class="fa-solid fa-cart-shopping"></i>
              <span class=" position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                <div class="cart_num">{{request.user.cart_number}}</div>
                <span class="visually-hidden">unread messages</span>
              </span>
            </button>

          </a>
        </li>
        <li>

          <div class="btn-group ">
            <a class="text-reset text-decoration-none" href="{% url 'profiles:customer_profile' %}"><button
                type="button" class="btn btn-dark text-capitalize">{{request.user.username}} <img
                  class="img-xs rounded-circle" src="{{request.user.profile_pic.url}}" width="30px" height="30px"
                  alt="">
              </button></a>
            <button type="button" class="btn btn-outline-warning dropdown-toggle dropdown-toggle-split"
              data-bs-toggle="dropdown" aria-expanded="false">
              <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-dark ">
              <li><a class="text-light dropdown-item " href="{% url 'profiles:customer_profile' %}">Profile</a></li>
              <li><a class="dropdown-item text-light" href="{% url 'orders:your_order' %}">My Order</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item text-light" href="{% url 'account:logout' %}">Logout</a></li>
            </ul>
          </div>
        </li>



        {% else %}
        <li>
          <div class="btn-group">
            <a href="{% url 'account:login' %}" class="text-reset text-decoration-none"> <button type="button"
                class="btn btn-warning">LOGIN </button></a>
            <button type="button" class="btn btn-warning dropdown-toggle dropdown-toggle-split"
              data-bs-toggle="dropdown" aria-expanded="false">
              <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'account:create_account' %}">Create Account</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'password_reset' %}">Forgot Password</a></li>
            </ul>
          </div>
        </li>
        {% endif %}


      </ul>
    </div>
  </div>
</nav>