account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import CustomLoginForm, CustomPasswordResetForm, CustomSetPasswordForm
from account import views
app_name = 'account'
urlpatterns = [
    path('send-otp', views.send_otp, name = 'send_otp'),
    path('verify-otp', views.verify_otp, name ='verify_otp'),
    path('create-account/', views.userCreationView, name='create_account' ),
    path('login/', auth_views.LoginView.as_view
    (template_name='user/login.html', authentication_form =CustomLoginForm ,next_page= 'home'), name= 'login' ),
    path('logout/', views.logoutView, name='logout'),
    
    path('admin-login/', auth_views.LoginView.as_view
    (template_name='super_admin/login.html', authentication_form =CustomLoginForm ,next_page= 'super_admin:home'), name= 'admin_login' ),
    path('admin-creation', views.AdminCreationView.as_view(), name='admin_creation'),
    path('admin-logout', views.adminLogoutView, name='admin_logout'),

]

appleshop/urls.py
# ================== appleshop URL Configuration ===============

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.forms import CustomLoginForm, CustomPasswordResetForm, CustomSetPasswordForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('super-admin/', include('super_admin.urls', namespace = 'super_admin')),
    path('', include('home.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('offers/', include('offers.urls', namespace='offers')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('products/', include('products.urls', namespace='products')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('account/', include('account.urls', namespace='account')),

    path('password-reset/', auth_views.PasswordResetView.as_view
    (template_name = 'user/password_reset.html', form_class = CustomPasswordResetForm), name = 'password_reset'),
    path('password-rest-done/', auth_views.PasswordResetDoneView.as_view
    (template_name = 'user/password_reset_done.html'), name = 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view
    (template_name = 'user/password_reset_confirm.html', form_class = CustomSetPasswordForm), name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view
    (template_name = 'user/password_reset_complete.html'), name = 'password_reset_complete'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart import views
app_name = 'cart'
urlpatterns = [
    
    path('', views.cartView, name = 'cart'),

    path('add-to-cart/', views.addToCartView, name= 'add_to_cart'),
    path('add-to-cart/<str:pk>/', views.addToCartBeforeLoginView, name= 'add_to_cart_brfore_login'),
    path('change-qty/', views.changeQtyView, name  = 'change_qty'),

]

profiles/urls.py
from django.urls import path
from profiles import views
app_name = 'profiles'
urlpatterns = [
    path('customer-profile/', views.CustomerProfileView.as_view(), name = 'customer_profile'),
    path('admin-profile/', views.AdminProfileView.as_view(), name = 'admin_profile'),
    path('address/', views.addressView, name = 'address'),
    path('address-delete/', views.addressDeleteView, name = 'address_delete'),
    path('address-edit/', views.addressEdit, name = 'address_edit'),
    path('address-default/', views.addressDefaultView, name = 'address_dafault'),
]

super_admin/urls.py
from django.urls import path
from super_admin import views

app_name = 'super_admin'
urlpatterns = [
    path('',views.homeView, name='home'),
    path('chart/',views.homeView, name='home'),

    path('category-add',views.CategoryAddView.as_view(), name='category_add'),
    path('category-list/', views.categoryListView, name= 'category_list'),
    path('category-details/<str:pk>', views.categoryDetailsView, name= 'category_details'),
    path('category-edit/<str:pk>', views.CategoryEditView.as_view(), name= 'category_edit'),
    path('category-delete/<str:pk>', views.categoryDeleteView, name= 'category_delete'),

    path('product-add',views.ProductAddView.as_view(), name='product_add'),
    path('product-list/', views.productListView, name= 'product_list'),
    path('product-details/<str:pk>', views.productDetailsView, name= 'product_details'),
    path('product-edit/<str:pk>', views.ProductEditView.as_view(), name= 'product_edit'),
    path('product-delete/<str:pk>', views.productDeleteView, name= 'product_delete'),

    path('coupon-add',views.couponAddView, name='coupon_add'),
    path('coupon-list/', views.couponListView, name= 'coupon_list'),
    path('coupon-edit/<str:pk>', views.CouponEditView.as_view(), name= 'coupon_edit'),
    path('coupon-delete/<str:pk>', views.couponDeleteView, name= 'coupon_delete'),

    path('order-list/', views.OrderListView.as_view(), name= 'order_list'),

    path('customer-list/', views.customerListView, name= 'customer_list'),
    path('admin-list/', views.adminListView, name= 'admin_list'),
    path('admin-request-list/', views.AdminRequestListView.as_view(), name= 'admin_request_list'),


]

super_admin/models.py
from django.db import models

# Create your models here.

super_admin/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.views import View
from super_admin.form import CategoryDetailsForm, ProductDetailsForm, CouponForm, OrderStatusForm, AdminForm
from django.db.models import Sum
from account.decorators import admin_login_required
from django.http import JsonResponse

from products.models import Product
from category.models import Category
from orders.models import Order
from offers.models import Coupon
from account.models import CustomUser

import datetime
from datetime import timedelta


# Create your views here.

@admin_login_required
def homeView(request):

    # ===========chart data by ajax request======
    if request.method == 'POST':
        order_success = Order.objects.filter(status = 'success').count()
        order_shipped = Order.objects.filter(status = 'shipped').count()
        order_deliverd = Order.objects.filter(status = 'deliverd').count()
        order_cancelled = Order.objects.filter(status = 'cancelled').count()

    # ========mothly product sale=========

        date_today = datetime.date.today()

        last_one_month = date_today - timedelta(days=30)
        second_last_month = last_one_month - timedelta(days=30)
        third_last_month = second_last_month - timedelta(days=30)
        fourth_last_month = third_last_month - timedelta(days=30)
        fifth_last_month = fourth_last_month - timedelta(days=30)
        sixth_last_month = fifth_last_month - timedelta(days=30)

        product_sale_1 = Order.objects.filter(updated_at__range=[last_one_month, date_today], status = 'deliverd').aggregate(last_one_month = Sum('total_amount'))
        product_sale_2 = Order.objects.filter(updated_at__range=[second_last_month, last_one_month], status = 'deliverd').aggregate(second_last_month = Sum('total_amount'))
        product_sale_3 = Order.objects.filter(updated_at__range=[third_last_month, second_last_month], status = 'deliverd').aggregate(third_last_month = Sum('total_amount'))
        product_sale_4 = Order.objects.filter(updated_at__range=[fourth_last_month, third_last_month], status = 'deliverd').aggregate(fourth_last_month = Sum('total_amount'))
        product_sale_5 = Order.objects.filter(updated_at__range=[fifth_last_month, fourth_last_month], status = 'deliverd').aggregate(fifth_last_month = Sum('total_amount'))
        product_sale_6 = Order.objects.filter(updated_at__range=[sixth_last_month, fifth_last_month], status = 'deliverd').aggregate(sixth_last_month = Sum('total_amount'))

        last_month_sale = product_sale_1.get('last_one_month')
        second_last_month_sale = product_sale_2.get('second_last_month')
        third_last_month_sale = product_sale_3.get('third_last_month')
        fourth_last_month_sale = product_sale_4.get('fourth_last_month')
        fifth_last_month_sale = product_sale_5.get('fifth_last_month')
        sixth_last_month_sale = product_sale_6.get('sixth_last_month')
        order_status = [order_success, order_shipped, order_deliverd, order_cancelled]
        monthly_sale = [
            sixth_last_month_sale,
            fifth_last_month_sale,
            fourth_last_month_sale,
            third_last_month_sale,
            second_last_month_sale,
            last_month_sale,
        ]





        chart_data = { 
            'order_status' : order_status,
            'monthly_sale' : monthly_sale
                }
        return JsonResponse(chart_data , safe=False)

    # ============total quantity of remaining products============
    # r_qty = Product.objects.aggregate(total_product_qty = Sum('qty'))

    # ============total quantity of deliverd products============
    # o_qty = Order.objects.aggregate(total_product_qty = Sum('qty'))



    # ============total revenue============
    products = Product.objects.all()
    total_revenue = 0
    for product in products:
        selling_price = product.selling_price
        qty = product.qty
        total = selling_price*qty
        total_revenue+=total

    # ============total cost============
    products = Product.objects.all()
    total_cost = 0
    for product in products:
        cost_price = product.cost_price
        qty = product.qty
        total = cost_price*qty
        total_cost+=total

    try:
    # ============total sales==========
        total_amount = Order.objects.filter(status = 'deliverd').aggregate(total_sale = Sum('total_amount'))
        total_sale = total_amount.get('total_sale')

        # ========total cost of saled product=====
        total_sale_cost = Order.objects.filter(status = 'deliverd').aggregate(total_saled_cost = Sum('total_cost'))
        total_saled_cost = total_sale_cost.get('total_saled_cost')

        # ===========total profit=========
        total_profit = total_sale-total_saled_cost


    except:
            # ============total sales==========
        total_amount = 0
        total_sale = 0

        # ========total cost of saled product=====
        total_sale_cost = 0
        total_saled_cost = 0

        # ===========maximum profit=========
        total_profit = 0


    # ===========maximum profit=========
    maximum_profit = total_revenue-total_cost


    context = {
        'total_revenue' : total_revenue,
        'total_cost' : total_cost,
        'maximum_profit' : maximum_profit,
        'total_sale' : total_sale,
        'total_saled_cost' : total_saled_cost,
        'total_profit' : total_profit,

    }

    return render(request, 'super_admin/home.html',context)


    


@method_decorator(admin_login_required, name='dispatch')
class CategoryAddView(View):
    def get(self, request):
        form = CategoryDetailsForm()
        context = {'form' : form}
        return render(request, 'super_admin/category_add.html', context)
    def post(self, request):
        form = CategoryDetailsForm(request.POST, request.FILES)
        if form.is_valid():
            prod_name = form.cleaned_data.get('name')
            print('=========', prod_name)
            try:
                same_prod = Category.objects.get(name__iexact = prod_name)
                print('=========', same_prod)
                messages.info(request, 'Category with same name already exist!')
                context = {'form' : form}
                return render(request, 'super_admin/category_add.html', context)                
            except:
                form.save()
                messages.success(request, 'New category added successfuly')
                return redirect('super_admin:category_add')
        messages.error(request, 'Form is not valid')
        return redirect('super_admin:category_add')

@admin_login_required
def categoryListView(request):
    categorys = Category.objects.all()
    context = {'categorys' : categorys}
    return render(request, 'super_admin/category_list.html', context )

@admin_login_required
def categoryDetailsView(request, pk):
    category = Category.objects.get(id=pk)
    context = {'category' : category}
    return render(request, 'super_admin/category_details.html', context)

@method_decorator(admin_login_required, name='dispatch')
class CategoryEditView(View):
    def get(self, request, pk):
        category = Category.objects.get(id=pk)
        form = CategoryDetailsForm(instance=category)
        context = {'form' : form}
        return render(request, 'super_admin/category_add.html', context)
    def post(self, request, pk):
        category = Category.objects.get(id=pk)
        form = CategoryDetailsForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category edited successfuly')
            return redirect('super_admin:category_list')
        messages.error(request, 'Form is not valid')
        return redirect('super_admin:category_add')

@method_decorator(admin_login_required, name='dispatch')
def categoryDeleteView(request, pk):
    category = Category.objects.get(id=pk)
    category.delete()
    messages.info(request, 'Category deleted!')
    return redirect('super_admin:category_list')









@method_decorator(admin_login_required, name='dispatch')
class ProductAddView(View):
    def get(self, request):
        form = ProductDetailsForm()
        context = {'form' : form}
        return render(request, 'super_admin/product_add.html', context)
    def post(self, request):
        form = ProductDetailsForm(request.POST, request.FILES)
        context = {'form' : form}
        if form.is_valid():
            form.save()
            messages.success(request, 'New product added successfuly')
            return redirect('super_admin:product_add')
        messages.error(request, 'Form is not valid')
        return render(request, 'super_admin/product_add.html', context)

@admin_login_required
def productListView(request):
    products = Product.objects.all()
    context = {'products' : products}
    return render(request, 'super_admin/product_list.html', context )

@admin_login_required
def productDetailsView(request, pk):
    product = Product.objects.get(id=pk)
    context = {'product' : product}
    return render(request, 'super_admin/product_details.html', context)

@method_decorator(admin_login_required, name='dispatch')
class ProductEditView(View):
    def get(self, request, pk):
        product = Product.objects.get(id=pk)
        form = ProductDetailsForm(instance=product)
        context = {'form' : form}
        return render(request, 'super_admin/product_add.html', context)
    def post(self, request, pk):
        product = Product.objects.get(id=pk)
        form = ProductDetailsForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product edited successfuly')
            return redirect('super_admin:product_list')
        messages.error(request, 'Form is not valid')

templates/super_admin/includes/footer.html
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © cb-apple-shop
            2022</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">
            Apple shop admin panel.
        </span>
    </div>
</footer>

templates/super_admin/includes/navbar.html
{% load static %}
<nav class="navbar p-0 fixed-top d-flex flex-row">
  <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
    <a class="navbar-brand" href="{% url 'super_admin:home' %}"><i class="fa-solid fa-apple-whole"></i>&nbspshop</a>
  </div>
  <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
    <button id="nav-toggler-btn" class="navbar-toggler navbar-toggler align-self-center border-0"
      data-bs-toggle="minimize">
      <span class="fa-solid fa-bars fs-4"></span>
    </button>
    <ul class="navbar-nav w-100">
      <li class="nav-item w-100 px-5 mt-2">
        <div id="theme_btn"></div>
      </li>
    </ul>
    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item dropdown d-none d-lg-block">
        <a class="nav-link btn btn-success create-new-button" id="createbuttonDropdown" data-bs-toggle="dropdown"
          aria-expanded="false" href="">+ Add</a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list"
          aria-labelledby="createbuttonDropdown">
          <div class="dropdown-divider"></div>
          <a href="{% url 'super_admin:category_add' %}" class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="fa-solid fa-bars text-danger"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject ellipsis mb-1">Category</p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a href="{% url 'super_admin:product_add' %}" class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="fa-brands fa-product-hunt text-primary"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject ellipsis mb-1">Product</p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a href="{% url 'super_admin:coupon_add' %}" class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="fa-solid fa-sheet-plastic text-success"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject ellipsis mb-1">Coupon</p>
            </div>
          </a>
        </div>
      </li>


      <li class="nav-item dropdown">
        <a class="nav-link" id="profileDropdown" href="#" data-bs-toggle="dropdown">
          <div class="navbar-profile">
            <img class="img-xs rounded-circle" src="{{request.user.profile_pic.url}}" alt="">
            <p class="mb-0 d-none d-sm-block navbar-profile-name">{{request.user.username}}</p>
            <i class="fa-solid fa-caret-down ms-2"></i>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
          <h6 class="p-3 mb-0">Profile</h6>
          <div class="dropdown-divider"></div>
          <a href="{% url 'profiles:admin_profile' %}" class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="fa-solid fa-eye text-info"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject mb-1">View</p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a href="{% url 'account:admin_logout' %} " class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="fa-solid fa-arrow-right-from-bracket text-danger"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject mb-1">Log out</p>
            </div>
          </a>
        </div>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
      data-toggle="offcanvas">
      <span class="fa-solid fa-bars"></span>
    </button>
  </div>
</nav>

templates/super_admin/includes/sidebar.html
{% load static %}

<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
        <a class="sidebar-brand brand-logo text-decoration-none" href="{% url 'super_admin:home' %}"><i
                class="fa-solid fa-apple-whole"></i>&nbspshop</a>
        <a class="sidebar-brand brand-logo-mini " href="{% url 'super_admin:home' %}"><i
                class="fa-solid fa-apple-whole"></i></a>
    </div>
    <ul class="nav position-fixed">
        <li class="nav-item profile">
            <div class="profile-desc">
                <div class="profile-pic">
                    <div class="count-indicator">
                        <img class="img-xs rounded-circle " src="{{request.user.profile_pic.url}}" alt="">
                        <span class="count bg-success"></span>
                    </div>
                    <div class="profile-name">
                        <h5 class="mb-0 font-weight-normal">{{request.user.username}}</h5>
                        {% if request.user.is_active %}
                        <span>Active</span>
                        {% else %}
                        <span>Not Active</span>
                        {% endif %}
                    </div>
                </div>
                <div class="dropdown">
                    <a role="button" id="profile-dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-solid fa-ellipsis-vertical text-muted"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list"
                        aria-labelledby="profile-dropdown">
                        <li>
                            <a href="{% url 'profiles:admin_profile' %}" class="dropdown-item preview-item">
                                <div class="preview-thumbnail">
                                    <div class="preview-icon bg-dark rounded-circle">
                                        <i class="fa-solid fa-eye text-info"></i>
                                    </div>
                                </div>
                                <div class="preview-item-content">
                                    <p class="preview-subject ellipsis mb-1 text-small">View</p>
                                </div>
                            </a>
                        </li>
                        <div class="dropdown-divider"></div>
                        <li>
                            <a href="{% url 'account:admin_logout' %}" class="dropdown-item preview-item">
                                <div class="preview-thumbnail">
                                    <div class="preview-icon bg-dark rounded-circle">
                                        <i class="fa-solid fa-arrow-right-from-bracket text-danger"></i>
                                    </div>
                                </div>
                                <div class="preview-item-content">
                                    <p class="preview-subject ellipsis mb-1 text-small">Logout</p>
                                </div>
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link btn btn-success" data-toggle="collapse" href="#add" aria-expanded="false"
                aria-controls="add">
                <span class="menu-icon">
                    <i class="fa-solid fa-circle-plus text-center text-dark fs-1"></i> </span>
                <span class="menu-title">Add</span>

            </a>
            <div class="collapse" id="add">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a class="nav-link" href="{% url 'super_admin:category_add' %}"> Category </a>
                    </li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'super_admin:product_add' %}"> Product
                        </a></li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'super_admin:coupon_add' %}"> Coupon

                        </a></li>
                </ul>
            </div>
        </li>

        <li class="nav-item nav-category">
            <span class="nav-link">Navigation</span>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'super_admin:home' %}">
                <span class="menu-icon">
                    <i class="fa-solid fa-chart-line text-info"></i>
                </span>
                <span class="menu-title">Dashboard</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'super_admin:category_list'%}">
                <span class="menu-icon">
                    <i class="fa-solid fa-bars"></i>
                </span>
                <span class="menu-title">Category</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'super_admin:product_list'%}">
                <span class="menu-icon">
                    <i class="fa-brands fa-product-hunt"></i>
                </span>
                <span class="menu-title">Product</span>
            </a>
        </li>

        <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'super_admin:coupon_list'%}">
                <span class="menu-icon">
                    <i class="fa-solid fa-sheet-plastic"></i>
                </span>
                <span class="menu-title">Coupon</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'super_admin:order_list'%}">
                <span class="menu-icon">
                    <i class="fa-solid fa-cart-shopping"></i>
                </span>
                <span class="menu-title">Orders</span>
            </a>
        </li>
        <li class="nav-item menu-items dropdown" style="height:500px;">
            <a role="button" class="nav-link" id="user" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="menu-icon">
                    <i class="fa-solid fa-users"></i>
                </span>
                <span class="menu-title">Users</span>

            </a>
            <div class="dropdown-menu border-0" id="user">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a class="nav-link" href="{% url 'super_admin:admin_list' %}"> Admin </a>
                    </li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'super_admin:customer_list' %}"> Customer
                        </a></li>
                    {% if request.user.is_superadmin %}
                    <li class="nav-item"> <a class="nav-link" href="{% url 'super_admin:admin_request_list' %}"> Admin
                            Request
                        </a></li>
                    {% endif %}
                </ul>
            </div>
        </li>

    </ul>
</nav>