account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import CustomLoginForm, CustomPasswordResetForm, CustomSetPasswordForm
from account import views
app_name = 'account'
urlpatterns = [
    path('send-otp', views.send_otp, name = 'send_otp'),
    path('verify-otp', views.verify_otp, name ='verify_otp'),
    path('create-account/', views.userCreationView, name='create_account' ),
    path('login/', auth_views.LoginView.as_view
    (template_name='user/login.html', authentication_form =CustomLoginForm ,next_page= 'home'), name= 'login' ),
    path('logout/', views.logoutView, name='logout'),
    
    path('admin-login/', auth_views.LoginView.as_view
    (template_name='super_admin/login.html', authentication_form =CustomLoginForm ,next_page= 'super_admin:home'), name= 'admin_login' ),
    path('admin-creation', views.AdminCreationView.as_view(), name='admin_creation'),
    path('admin-logout', views.adminLogoutView, name='admin_logout'),

]

cart/urls.py
from django.urls import path
from cart import views
app_name = 'cart'
urlpatterns = [
    
    path('', views.cartView, name = 'cart'),

    path('add-to-cart/', views.addToCartView, name= 'add_to_cart'),
    path('add-to-cart/<str:pk>/', views.addToCartBeforeLoginView, name= 'add_to_cart_brfore_login'),
    path('change-qty/', views.changeQtyView, name  = 'change_qty'),

]

home/urls.py
from django import views
from django.urls import path
from home import views

urlpatterns = [
    path('', views.homeView, name='home')
]

orders/urls.py
from django.urls import path
from orders import views
app_name = 'orders'
urlpatterns = [
    path('single-order/<str:pk>/', views.singleOrderView, name = 'single_order'),
    path('cart-order/', views.cartOrderView, name = 'cart_order'),
    path('your-order/', views.yourOrderView, name = 'your_order'),

    path('payment', views.paymentView),
    path('razorpay/', views.razorpayKey)

]

products/urls.py
from django.urls import path
from products import views
app_name = 'products'

urlpatterns = [
    path('product-list/<str:pk>/', views.productListView, name = 'product_list'),
    path('product-details/<str:pk>/', views.productDetailsView, name = 'product_details'),
]

profiles/urls.py
from django.urls import path
from profiles import views
app_name = 'profiles'
urlpatterns = [
    path('customer-profile/', views.CustomerProfileView.as_view(), name = 'customer_profile'),
    path('admin-profile/', views.AdminProfileView.as_view(), name = 'admin_profile'),
    path('address/', views.addressView, name = 'address'),
    path('address-delete/', views.addressDeleteView, name = 'address_delete'),
    path('address-edit/', views.addressEdit, name = 'address_edit'),
    path('address-default/', views.addressDefaultView, name = 'address_dafault'),
]

account/models.py
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager, PermissionsMixin)
from cropperjs.models import CropperImageField

# ================= custom user model ===============

class CustomBaseUserManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, mobile, password= None ):
        if not email:
            raise ValueError("User must have an email address")
        if not username:
            raise ValueError("User must have an username")

        user = self.model(
            first_name =first_name,
            last_name =last_name,
            username = username,
            email = self.normalize_email(email),
            mobile = mobile
        )

        user.set_password(password)
        user.save(using = self._db)
        return user

    def create_superuser(
        self, username, email, password, mobile, first_name='', last_name= ''
    ):
        user = self.create_user(
            first_name =first_name,
            last_name =last_name,
            username = username,
            email = self.normalize_email(email),
            mobile = mobile,
            password= password
        )

        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.is_verified = True
        user.save(using=self._db)
        return user




class CustomUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=55,null=True, blank=True)
    last_name = models.CharField(max_length=55,null=True, blank=True)
    username  =models.CharField(max_length=55, unique=True)
    email = models.EmailField(max_length=55, unique=True)
    mobile = models.CharField(max_length=10, unique=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superadmin = models.BooleanField(default=False)
    is_admin_request = models.BooleanField(default=False)

    GENDER_CHOICES = (
        ('male' , 'Male'),
        ('female' , 'Female'),
        ('other' , 'Other')

    )
    profile_pic = models.ImageField(upload_to = 'user_pro_pic', default='default/pro_pic.png')
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES, null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'mobile'
    REQUIRED_FIELDS = ['username', 'email' ]

    objects = CustomBaseUserManager()

    def __str__(self):
        return self.username

    def full_name(self):
        return f"{self.first_name} {self.last_name}"   
    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True
    def cart_number(self):
        no_of_cart_items = self.u_cart.count()
        return no_of_cart_items

class UserMobile(models.Model):
    mobile = models.CharField(max_length=10)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.mobile

cart/models.py
from django.db import models
from account.models import CustomUser
from products.models import Product

class Cart(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='u_cart')
    product = models.ForeignKey(Product, on_delete=models.CASCADE )
    qty = models.PositiveIntegerField(default=1 )

    def __str__(self):

        return self.product.name

    def totalPrice(self):
        total_price = self.product.selling_price * self.qty
        return int(total_price)

orders/models.py
from django.db import models

STATUS_CHOICES = (
    ('success', 'success'),
    ('shipped', 'shipped'),
    ('out of selivery', 'out of delivery'),
    ('deliverd', 'deliverd'),
    ('cancelled', 'cancelled'),
)
class Order(models.Model):
    user = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    product = models.CharField(max_length=100)
    product_id = models.PositiveIntegerField()
    product_selling_price = models.FloatField()
    qty = models.PositiveIntegerField()
    total_amount = models.FloatField(null=True)
    total_cost = models.FloatField(default=0)
    image = models.ImageField(upload_to = 'order_image')
    coupon = models.PositiveIntegerField(null=True, blank=True)
    payment = models.CharField(max_length=100)
    payment_id = models.CharField(max_length=100, null=True, blank=True)
    tracking_id = models.CharField(max_length=100)
    status = models.CharField(max_length=100, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.product

profiles/models.py
from django.db import models
from account.models import CustomUser

STATE_CHOICES = (
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Bihar', 'Bihar'),
    ('Chhattisgarh', 'Chhattisgarh'),
    ('Goa','Goa'),
    ('Gujarat', 'Gujarat'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh'),
    ('Jharkhand', 'Jharkhand'),
    ('Karnataka', 'Karnataka'),
    ('Kerala', 'Kerala'),
    ('Madhya Pradesh', 'Madhya Pradesh'),
    ('Maharashtra', 'Maharashtra'),
    ('Manipur', 'Manipur'),
    ('Meghalaya', 'Meghalaya'),
    ('Mizoram', 'Mizoram'),
    ('Nagaland', 'Nagaland'),
    ('Odisha', 'Odisha'),
    ('Punjab', 'Punjab'),
    ('Rajasthan', 'Rajasthan'),
    ('Sikkim', 'Sikkim'),
    ('Tamil Nadu', 'Tamil Nadu'),
    ('Telangana', 'Telangana'),
    ('Tripura', 'Tripura'),
    ('Uttar Pradesh', 'Uttar Pradesh'),
    ('Uttarakhand', 'Uttarakhand'),
    ('West Bengal', 'West Bengal'),
    ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'),
    ('Chandigarh', 'Chandigarh'),
    ('Dadra & Nagar Haveli and Daman & Diu', 'Dadra & Nagar Haveli and Daman & Diu'),
    ('Delhi', 'Delhi'),
    ('Jammu and Kashmir', 'Jammu and Kashmir'),
    ('Lakshadweep', 'Lakshadweep'),
    ('Puducherry', 'Puducherry'),
    ('Ladakh', 'Ladakh')
)


class CustomerAddress(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    address = models.TextField()
    state = models.CharField(max_length=100, choices=STATE_CHOICES)
    pin = models.PositiveIntegerField()
    mob = models.PositiveIntegerField()
    edit = models.BooleanField(default=False)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.name


   

cart/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

from products.models import Product
from cart.models import Cart


@login_required(login_url='account:login')
def addToCartView(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        product = Product.objects.get(id = product_id)
        Cart.objects.create(user = request.user, product = product)
        data = { 
            'status' : 'Product added successfully'
        }
        return JsonResponse(data)

@login_required(login_url='account:login')
def addToCartBeforeLoginView(request, pk):
    product = Product.objects.get(id = pk)
    cart = Cart.objects.filter(product = product, user = request.user)
    if cart:
        return redirect('products:product_details', pk=str(pk))
    else:
        Cart.objects.create(user = request.user, product = product)
        return redirect('products:product_details', pk=str(pk))

@login_required(login_url='account:login')
def cartView(request):
    # =========== product revove from cart =============
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        cart_product = Cart.objects.get(user = request.user, product = product_id)
        cart_product.delete()
        return JsonResponse({'status' : 'Product removed from cart'})

    carts = Cart.objects.filter(user = request.user)
    no_of_items = carts.count()
    total_marking_price =0
    total_amount = 0
    for cart in carts:
        total_marking_price += cart.product.marking_price * cart.qty
        total_amount = total_amount + (cart.product.selling_price * cart.qty)
    discount = total_marking_price - total_amount
    cart = Cart.objects.filter(user = request.user)

    context = {
    'cart' : cart,
    'no_of_items' : no_of_items,
    'total_marking_price' : total_marking_price,
    'discount' : discount,
    'total_amount' : total_amount,
    }

    return render (request, 'user/cart.html', context)

def changeQtyView(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        qty = request.POST.get('quantity')
        cart = Cart.objects.get(user = request.user, product = product_id)
        cart.qty = qty
        cart.save()
        return JsonResponse({'status' : 'qty changed successfully'})

home/views.py
from django.shortcuts import render
from category.models import Category
from products.models import Product


def homeView(request):
    categories = Category.objects.all().order_by('order_by')
    products_in_home = Product.objects.filter(is_visible_home_img = True).order_by('home_img_order')

    context = {
    'categories' : categories,
    'products_in_home' : products_in_home
    }
    return render(request, 'user/home.html', context)

profiles/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.views import View
from django.utils.decorators import method_decorator
from profiles.form import AddressForm, ProfileForm
from profiles.models import CustomerAddress 
from account.models import CustomUser

@method_decorator(login_required(login_url='account:login'), name='dispatch')
class CustomerProfileView(View):
    
    def get(self, request):
        form = AddressForm
        user = CustomUser.objects.get(username = request.user.username)
        profiles_form = ProfileForm(instance= user)
        addresses = CustomerAddress.objects.filter(user = request.user).order_by('-default')
        context = {
            'addresses' : addresses,
            'form' : form,
            'profiles_form' : profiles_form
        }
        return render(request, 'user/profile.html', context)
    def post(self, request):
        profile_form = ProfileForm( request.POST, request.FILES, instance= request.user)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Profile edited successfuly')
            return redirect('profiles:customer_profile')
        messages.error(request, 'Invalid data')
        return redirect('profiles:coustomer_profile')

@method_decorator(login_required(login_url='account:login'), name='dispatch')
class AdminProfileView(View):
    def get(self, request):
        profile_form = ProfileForm(instance= request.user)
        context = {
            'profile_form' : profile_form
        }
        return render(request, 'super_admin/profile.html', context)

    def post(self, request):
        user_profile_form = ProfileForm( request.POST, request.FILES, instance= request.user)
        if user_profile_form.is_valid():
            user_profile_form.save()
            messages.success(request, 'Profile edited successfuly')
            return redirect('profiles:admin_profile')
        messages.error(request, 'Invalid data')
        return redirect('profiles:admin_profile')



@login_required(login_url='account:login')
def addressView(request):

    if request.method == 'POST':
        default_address = CustomerAddress.objects.filter(user = request.user, default = True)
        for address in default_address:
            address.default = False
            address.save()
        name = request.POST.get('name')
        address = request.POST.get('address')
        state = request.POST.get('state')
        pin = request.POST.get('pin')
        mob = request.POST.get('mob')

        try:
            edit_address = CustomerAddress.objects.get(edit = True)
            edit_address.name = name
            edit_address.address = address
            edit_address.state = state
            edit_address.pin = pin
            edit_address.mob = mob
            edit_address.edit = False
            edit_address.default = True
            edit_address.save()

            print('update')
        except:
            CustomerAddress.objects.create(
            user = request.user, 
            name = name, 
            address = address, 
            state = state, 
            pin = pin, 
            mob = mob, 
            default = True
            )
            data = { 
                'status' : 'Product added successfully'
            }
            print('create')
            return JsonResponse(data)
    
    form = AddressForm
    context = {'form' : form }
    return render(request, 'user/profile.html', context)

@login_required(login_url='account:login')
def addressDefaultView(request):
    if request.method == 'POST':
        address_id = request.POST.get('address_id')
        all_address = CustomerAddress.objects.filter(user = request.user)
        for address in all_address:
            address.default = False
            address.save()
        address = CustomerAddress.objects.get(user = request.user, id = address_id)
        address.default = True
        address.save()
        data = { 
            'status' : 'set to default'
        }
        return JsonResponse(data)

@login_required(login_url='account:login')
def addressDeleteView(request):
    if request.method == 'POST':
        address_id = request.POST.get('address_id')
        address = CustomerAddress.objects.get(user = request.user, id = address_id)
        address.delete()
        data = { 
            'status' : 'Product added successfully'
        }
        return JsonResponse(data)


@login_required(login_url='account:login')
def addressEdit(request):
    if request.method == 'POST':
        address_id = request.POST.get('address_id')
        address = CustomerAddress.objects.get(user = request.user, id = address_id)
        address.edit = True
        address.save()
        data = {
            'name' : address.name,
            'address' : address.address,
            'state' : address.state,
            'pin' : address.pin,
            'mob' : address.mob
        }
        return JsonResponse(data)

templates/user/home.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %} Home {% endblock title %}
{% block content %}

<!-- ================slider=====================  -->

<header>
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators .text-muted">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
        aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
        aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
        aria-label="Slide 3"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3"
        aria-label="Slide 4"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active carousel1">
        <div class="carousel-caption d-none d-md-block">
          <h5></h5>
          <p></p>
        </div>
      </div>
      <div class="carousel-item carousel2">
        <div class="carousel-caption d-none d-md-block">
          <h5></h5>
          <h3>Light. Bright. Full of might</h3>
        </div>
      </div>
      <div class="carousel-item carousel3">
        <div class="carousel-caption d-none d-md-block">
          <h5>You’ve never heard colour like this.</h5>
          <p>Made to fill every room with rich, 360‑degree audio. Now available in five colours.</p>
        </div>
      </div>
      <div class="carousel-item carousel4">
        <div class="carousel-caption d-none d-md-block">
          <h5>Oh.So.Pro</h5>
          <p></p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="text-secondary fs-1">
        <i class="fa fa-angle-left" aria-hidden="true"></i>
      </span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="text-secondary fs-1">
        <i class="fa fa-angle-right" aria-hidden="true"></i>
      </span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</header>

<!-- ====================category================ -->

<div class="container p-lg-5">
  <div class="row products_category">
    {% for category in categories %}
    <div class="col-lg-2 col-4 mt-3">
      <a href="{% url 'products:product_list' category.category %}">
        <img class="items" src="{{category.image.url}}" alt="" w-100 />
      </a>
    </div>
    {% endfor %}
  </div>
</div>

<!-- ========== home images =========== -->
<div class="home_products">
  {% for product in products_in_home %}
  {% if product.home_img %}
  <div class="row pt-5">
    <div class="col-12 text-center">
      <a href="{% url 'products:product_details' product.id %}" class="">
        <img src="{{product.home_img.url}}" class="home_img rounded-pill" style="max-width: 100%;">
      </a>
    </div>
  </div>

  {% endif %}
  {% endfor %}
</div>

{% endblock %}

templates/user/login.html
{% extends 'user/base.html' %}
{% block title %} Login {% endblock title %}
{% block content %}

<div class="container my-lg-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <div class="shadow p-3 mb-5 bg-body rounded">
                <h3>Login</h3>
                <hr>

                {% if form.non_field_errors %} {% for error in form.non_field_errors %}
                <p class="alert alert-danger my-3">{{error}}</p>
                {% endfor %} {% endif %}

                <form action="" method="post">
                    {% csrf_token %}

                    {% for form in form %}
                    <div class="form-group my-4">
                        {{form}}
                        <small class="text-danger">{{form.errors|striptags }}</small>
                    </div>
                    {% endfor %}

                    <div class="row mt-3">
                        <div class="col-lg-6 p-lg-3  ">
                            <button class="btn btn-warning px-5  me-auto fw-bold w-100">LOGIN</button>
                        </div>
                        <div class="col-lg-6 p-lg-3 mt-3 mt-lg-0">
                            <a class="btn btn-primary px-5  fw-bold w-100" href="{% url 'account:send_otp' %}">
                                SIGNUP
                            </a>
                        </div>
                    </div>
                    <a class="text-decoration-none" href="{% url 'password_reset' %}">
                        <p class="text-primary text-center m-3 fw-bold"> Forgot Password ?</p>
                    </a>

                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/user/password_reset.html
{% extends 'user/base.html' %}
{% block title %} Password Rest {% endblock title %}
{% block content %}

<div class="container my-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <div class="shadow p-3 mb-5 bg-body rounded">
                <h3>Password Reset</h3>
                <hr>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-group my-4">
                        {{form}}
                        <span class="text-danger">{{form.errors | striptags }}</span>
                    </div>
                    <p class="text-secondary">Generate a one-use only link for resetting password and send it to the
                        user email.</p>
                    <button class="btn btn-warning px-5 mt-5 fw-bold d-block mx-auto">SEND</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/user/product_details.html
{% extends 'user/base.html' %} {% load static %}
{% block title %} Product Details {% endblock title %}
{% block content %}
{% block link %}
<script src="https://unpkg.com/js-image-zoom/js-image-zoom.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-image-zoom/js-image-zoom.min.js"></script>
{% endblock %}

<div class="row">
  <div class="col-lg-4 p-lg-3">
    <div class="shadow bg-body rounded p-lg-3">
      <div id="img-container" class="  prod_img_container">
        <img data-big-image="{{product.image1.url}}" id="product_img_id" class="prod_det_img tiksluszoom p-3 mb-5"
          src="{{product.image1.url}}" alt="" />
      </div>
      <div class="add_to_cart add_buy_container d-flex w-100">

        {% if product.qty > 0 %}
        {% csrf_token %}
        {% if alredy_in_cart and request.user.is_authenticated %}
        <a href="{% url 'cart:cart' %}" class="btn btn-warning py-2 fs-5 w-100">
          GO TO CART
          <span></span>
        </a>

        {% else %}
        {% if request.user.is_authenticated %}
        <a class="add_to_cart_btn btn btn-primary py-2 fs-5 w-100 ">
          <span class="spinner-border spinner-border-sm me-2 mb-1 fs-3 visually-hidden cart_spinner" role="status"
            aria-hidden="true"></span>
          ADD TO CART
        </a>

        {% else %}

        <a href="{% url 'cart:add_to_cart_brfore_login' product.id %}" class="btn btn-primary py-2 fs-5 w-100">ADD
          TO
          CART</a>

        {% endif %}
        {% endif %}

        <input type="hidden" class="product_id" value="{{product.id}}">
        <a href="{% url 'orders:single_order' product.id %}"
          class="buy_now_btn btn btn-success ms-lg-3 fs-5 w-100 py-2">
          BUY NOW
        </a>

        {% else %}

        <h4 class="text-danger text-center py-2 fs-5 w-100 bg-light w-100 mb-0">
          Out of Stock
        </h4>
        <a href="{% url 'home' %}" class="add_to_cart buy_now btn btn-light py-2 fs-5 ms-lg-3 w-100">
          BACK TO HOME
        </a>

        {% endif %}

      </div>
    </div>
  </div>
  <div class="col-lg-8 p-lg-5 mb-5 bg_white">
    <div class="p-2">
      <h3 class="d-inline">{{product.title}}</h3>

      {% if product.tag %}

      <span class="product_tag">{{product.tag}}</span>

      {% endif %}

      <h3 class="text-primary mt-3">₹{{product.selling_price | stringformat:'d'}}</h3>
      <h6 class="text-secondary text-decoration-line-through">₹{{product.marking_price }}</h6>
      <h4 class="text-success">{{discount}}% off</h4>
      <h6>Available offers</h6>
      <ol>
        <li>
          Bank Offer₹5000 Instant Discount on HDFC Credit Card, Credit and Debit
          EMIT&C
        </li>
        <li>Bank Offer5% Cashback on Flipkart Axis Bank CardT&C</li>
        <li>
          Special PriceGet extra ₹5000 off (price inclusive of discount)T&C
        </li>
        <li>FreebieClasses - 3 Class PackT&C</li>
      </ol>
      <h6>Highlights</h6>
      <ol>
        {% if product.os %}<p> {{product.os}} </p>{% endif %}
        {% if product.display %}<p> {{product.display}} </p>{% endif %}
        {% if product.processor %}<p> {{product.processor}} </p>{% endif %}
        {% if product.RAM %}<p> {{product.RAM}} RAM </p>{% endif %}
        {% if product.ROM %}<p> {{product.ROM}} ROM </p>{% endif %}
        {% if product.spec1 %}<p> {{product.spec1}} </p>{% endif %}
        {% if product.spec2 %}<p> {{product.spec2}} </p>{% endif %}
        {% if product.spec3 %}<p> {{product.spec3}} </p>{% endif %}
        {% if product.spec4 %}<p> {{product.spec4}} </p>{% endif %}
        {% if product.spec5 %}<p> {{product.spec5}} </p>{% endif %}
        {% if product.spec6 %}<p> {{product.spec6}} </p>{% endif %}
        {% if product.spec7 %}<p> {{product.spec7}} </p>{% endif %}
        {% if product.spec8 %}<p> {{product.spec8}} </p>{% endif %}
        {% if product.spec9 %}<p> {{product.spec9}} </p>{% endif %}
        {% if product.spec10 %}<p> {{product.spec10}} </p>{% endif %}
        {% if product.spec11 %}<p> {{product.spec11}} </p>{% endif %}
        {% if product.spec12 %}<p> {{product.spec12}} </p>{% endif %}
        {% if product.spec13 %}<p> {{product.spec13}} </p>{% endif %}
        {% if product.spec14 %}<p> {{product.spec14}} </p>{% endif %}
        {% if product.spec15 %}<p> {{product.spec15}} </p>{% endif %}
      </ol>
      <h6>About this item</h6>
      <ul>
        <li>
          {{product.description}}
        </li>
      </ul>
    </div>
    <div class="row"></div>
  </div>
</div>
</div>

<script src="{% static 'zoom/js/script.js' %}"></script>

{% endblock content %}

templates/user/send_otp.html
{% extends 'user/base.html' %}
{% block title %} Send OTP {% endblock title %}
{% block content %}

<div class="container my-lg-5">
    <div class="row d-flex justify-content-center">
        <div class="col-lg-6">
            <div class="shadow p-3 mb-5 bg-body rounded">
                <h3 class="my-3 text-center">User Creation Form</h3>
                <hr>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-group my-4">
                        <input type="number" name="mobile" maxlength="10" class="form-control"
                            placeholder="Enter Mobile" autofocus="" required="" id="id_mobile">
                        <small class="text-danger"></small>
                    </div>
                    <button type="submit" class="btn btn-success send_otp_btn">SEND OTP</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}